spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    group-id: data-compare-email-group

kafka:
  topic:
    data-compare-topic: data_comparing_email

aws:
  auth:
    static:
      key_id: ${AWS_KEY_ID:NA}
      access_key: ${AWS_ACCESS_KEY:NA}
      token: ${AWS_TOKEN:NA}
    profile:
      profile_name: ${AWS_PROFILE:NA}
    iam:
      enabled: ${AWS_IAM:false}
  s3:
    bucket-name: eq-data-compare
    region: ${S3_REGION:NA}
    url-expiration-hours: 48
  ses:
    source-email: user9@eqcdw.testinator.com