spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    group-id: data-compare-email-group

kafka:
  topic:
    data-compare-topic: ${KAFKA_TOPIC_NAME}

aws:
  region: ${AWS_REGION}
  ses:
    source-email: ${AWS_SES_SOURCE_EMAIL}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    url-expiration-hours: 48